export type Familia = {
  id: string;
  nome: string;
  quantas: string;
  resumo: string;
};

export type Carta = {
  n: number;
  nome: string;
  familia: Familia["id"];
  lugar: string;
  frase: string;
  palavras: [string, string, string];
  essencia: string;
  luz: string;
  sombra: string;
  ativacao: string;
  /** Caminho da ilustração em /public. Enquanto vazio, o site mostra um bloco cinza. */
  imagem?: string;
};

export const familias: Familia[] = [
  {
    id: "direcoes",
    nome: "Direções e Centro",
    quantas: "8 + 1 cartas",
    resumo:
      "Uma roda que começa no Leste, onde o sol nasce, e gira até voltar ao Centro. Cada direção é um jeito de se mover pela vida: chamar, dizer, guiar, transformar, recolher, lembrar, agir, dançar e, por fim, integrar.",
  },
  {
    id: "animais",
    nome: "Animais Mestres",
    quantas: "3 cartas",
    resumo:
      "A serpente, o puma e o condor. Os guardiões dos três mundos, cada um com uma medicina: trocar de pele, proteger com estratégia e ver de longe.",
  },
  {
    id: "mundos",
    nome: "Três Mundos",
    quantas: "3 cartas",
    resumo:
      "Inspirados na cosmovisão andina: Ukhu Pacha, o mundo de baixo, das raízes e da sombra fértil; Kay Pacha, o mundo do meio, onde a vida acontece; e Hanan Pacha, o mundo de cima, da inspiração.",
  },
  {
    id: "elementos",
    nome: "Quatro Elementos",
    quantas: "4 cartas",
    resumo:
      "Terra que sustenta, ar que sopra ideias, fogo que acende o novo e água que sente fundo. O corpo do oráculo.",
  },
  {
    id: "feminino",
    nome: "Arquétipos do Feminino",
    quantas: "7 cartas",
    resumo:
      "Rostos que toda mulher reconhece em si em algum momento: a filha selvagem, a amante, a mãe, a anciã, a xamã, a arquiteta e a guardiã.",
  },
  {
    id: "lua",
    nome: "Ciclo Lunar",
    quantas: "4 cartas",
    resumo:
      "Plantar no escuro, crescer, florescer, soltar. As quatro fases da lua como um mapa de qualquer processo que você esteja vivendo.",
  },
];

export const cartas: Carta[] = [
  {
    n: 1,
    nome: "A Visionária",
    familia: "direcoes",
    lugar: "Leste",
    frase: "Eu desperto com o Sol. Trago novos olhos ao mundo.",
    palavras: ["Visão", "Intuição", "Potencial"],
    essencia: "Visão clara que inicia o ciclo. Representa o chamado.",
    luz: "Capta possibilidades futuras e inspira o presente.",
    sombra: "Sonha demais, age de menos.",
    ativacao: "Observe o nascer do sol em silêncio. O que quer nascer com ele?",
    imagem: "/cartas/1.webp",
  },
  {
    n: 2,
    nome: "A Mensageira",
    familia: "direcoes",
    lugar: "Nordeste",
    frase: "Eu anuncio o invisível. Minha voz abre portais de sentido.",
    palavras: ["Comunicação", "Escuta", "Revelação"],
    essencia: "Expressa o invisível. Traduz a escuta em palavra.",
    luz: "Porta-voz do que precisa ser ouvido.",
    sombra: "Fala demais ou cala verdades.",
    ativacao: "Escreva uma carta que nunca foi dita. Leia em voz alta.",
    imagem: "/cartas/2.webp",
  },
  {
    n: 3,
    nome: "A Mestra Solar",
    familia: "direcoes",
    lugar: "Norte",
    frase: "Minha visão é ampla como o voo do condor. Eu sustento o céu.",
    palavras: ["Clareza", "Propósito", "Presença"],
    essencia: "Direção firme, mental, guia estruturante.",
    luz: "Enxerga o todo, orienta com sabedoria.",
    sombra: "Arrogância, rigidez, negação do mistério.",
    ativacao: "Desenhe seu mapa de propósito. Onde você está?",
    imagem: "/cartas/3.webp",
  },
  {
    n: 4,
    nome: "A Alquimista",
    familia: "direcoes",
    lugar: "Noroeste",
    frase: "Eu transbordo fogo e forma. Meu ventre é vulcão que transforma.",
    palavras: ["Transmutação", "Intensidade", "Poder"],
    essencia: "Transforma com arte. Cria novos compostos.",
    luz: "Converte dor em criação.",
    sombra: "Caótica, controladora, contida.",
    ativacao: "Acolha uma emoção incômoda. Como ela quer se expressar?",
    imagem: "/cartas/4.webp",
  },
  {
    n: 5,
    nome: "A Exploradora das Sombras",
    familia: "direcoes",
    lugar: "Oeste",
    frase: "Eu desço à noite da alma. Encontro tesouros no escuro.",
    palavras: ["Coragem", "Profundidade", "Recuperação"],
    essencia: "Espaço de recolhimento, término e integração.",
    luz: "Enfrenta o que foi negado.",
    sombra: "Fuga, negação, obsessão pelo submundo.",
    ativacao: "Escreva sobre um medo antigo. Leia em voz alta. Respire.",
    imagem: "/cartas/5.webp",
  },
  {
    n: 6,
    nome: "A Tecelã do Ancestral",
    familia: "direcoes",
    lugar: "Sudoeste",
    frase: "Eu costuro o silêncio com raízes. Sonho os mundos que virão.",
    palavras: ["Origem", "Memória", "Mistério"],
    essencia: "Cria sentido com fios invisíveis.",
    luz: "Guarda a sabedoria dos ciclos. Sonha com o futuro sem romper com o passado.",
    sombra: "Prende-se a histórias antigas, apego ao que foi.",
    ativacao: "Converse com uma mulher de sua linhagem. O que ela ainda te ensina?",
    imagem: "/cartas/6.webp",
  },
  {
    n: 7,
    nome: "A Curandeira",
    familia: "direcoes",
    lugar: "Sul",
    frase: "Eu deslizo como rio. Minha medicina é emoção em fluxo.",
    palavras: ["Cura", "Liberação", "Fluidez"],
    essencia: "Ação no mundo, presença no fazer.",
    luz: "Acolhe emoções e permite o movimento da vida.",
    sombra: "Estagna no drama ou no silêncio.",
    ativacao: "Escolha uma música que te faça chorar. Deixe a água sair.",
    imagem: "/cartas/7.webp",
  },
  {
    n: 8,
    nome: "A Artista Selvagem",
    familia: "direcoes",
    lugar: "Sudeste",
    frase: "Eu danço a forma do invisível. Minha criação é oferenda.",
    palavras: ["Expressão", "Intuição", "Rito"],
    essencia: "Movimento ritmado que expande a consciência.",
    luz: "Transforma experiência em beleza viva.",
    sombra: "Se bloqueia, se dispersa, duvida do valor do que cria.",
    ativacao: "Crie algo com as mãos agora. Sem julgamento.",
    imagem: "/cartas/8.webp",
  },
  {
    n: 9,
    nome: "A Integradora",
    familia: "direcoes",
    lugar: "Centro",
    frase: "Em mim, tudo encontra lugar. Eu sou a ponte entre mundos.",
    palavras: ["Síntese", "Alinhamento", "Totalidade"],
    essencia: "Coração do oráculo. Ponto de silêncio e totalidade.",
    luz: "Integra polaridades e gera coerência.",
    sombra: "Fragmentada, vive em extremos, evita o centro.",
    ativacao: "Desenhe dois opostos da sua vida atual. Onde eles se tocam?",
    imagem: "/cartas/9.webp",
  },
  {
    n: 10,
    nome: "A Condutora dos Ciclos",
    familia: "animais",
    lugar: "Serpente",
    frase: "Eu rastejo entre os mundos. Tua pele antiga não te serve mais.",
    palavras: ["Renovação", "Raiz", "Transição"],
    essencia: "Transforma pela raiz. Desfaz cascas.",
    luz: "Sabe a hora de deixar a pele velha para trás.",
    sombra: "Muda por fuga, ou se agarra à casca por medo.",
    ativacao: "Nomeie uma pele que já ficou pequena. Como seria sair dela?",
    imagem: "/cartas/10.webp",
  },
  {
    n: 11,
    nome: "A Guerreira Instintiva",
    familia: "animais",
    lugar: "Puma",
    frase: "Eu caminho sem medo. Minha força é o agora.",
    palavras: ["Força", "Proteção", "Estratégia"],
    essencia: "A força estratégica que protege e avança.",
    luz: "Age no tempo certo, com firmeza e foco.",
    sombra: "Ataca por medo, ou se esconde da própria força.",
    ativacao: "Fique de pé, pés firmes no chão. Onde você precisa colocar um limite?",
    imagem: "/cartas/11.webp",
  },
  {
    n: 12,
    nome: "A Sacerdotisa do Voo",
    familia: "animais",
    lugar: "Condor",
    frase: "Eu vejo o todo. Voo entre os sonhos e as montanhas.",
    palavras: ["Visão ampla", "Elevação", "Conexão"],
    essencia: "Visão ampla, voo espiritual, conexão elevada.",
    luz: "Enxerga além do problema e oferece perspectiva.",
    sombra: "Sobe tanto que se esquece do chão.",
    ativacao: "Olhe para sua questão como se estivesse a mil metros de altura. O que muda?",
    imagem: "/cartas/12.webp",
  },
  {
    n: 13,
    nome: "A Protetora do Subterrâneo",
    familia: "mundos",
    lugar: "Ukhu Pacha",
    frase: "Eu abraço o invisível. No fundo, tudo germina.",
    palavras: ["Raiz", "Incubação", "Profundidade"],
    essencia: "Mundo interior. Sombra fértil. Lugar de cura.",
    luz: "Nutre o que ainda não nasceu. Cuida do invisível com paciência.",
    sombra: "Esconde demais, reprime, desaparece.",
    ativacao: "Sente-se sobre a terra. Feche os olhos. O que se move sob você?",
    imagem: "/cartas/13.webp",
  },
  {
    n: 14,
    nome: "A Senhora do Presente",
    familia: "mundos",
    lugar: "Kay Pacha",
    frase: "Eu crio com os pés na terra. Aqui, agora, pulsa a realidade.",
    palavras: ["Concretude", "Ritmo", "Presença"],
    essencia: "Presente e cotidiano. Onde se age e se vive.",
    luz: "Está inteira no agora. Cria com firmeza e presença.",
    sombra: "Vive no automático ou no excesso de controle.",
    ativacao: "Toque três coisas perto de você. Sinta com o corpo todo.",
    imagem: "/cartas/14.webp",
  },
  {
    n: 15,
    nome: "A Dama Celeste",
    familia: "mundos",
    lugar: "Hanan Pacha",
    frase: "Eu olho para as estrelas. O cosmos sussurra através da minha intuição elevada.",
    palavras: ["Contemplação", "Presságio", "Direção"],
    essencia: "Mundo elevado. Inspiração e conexão espiritual.",
    luz: "Conecta-se ao propósito maior.",
    sombra: "Fuga do real, idealizações desconectadas.",
    ativacao: "Olhe para o céu. Faça uma pergunta. Espere o sinal.",
    imagem: "/cartas/15.webp",
  },
  {
    n: 16,
    nome: "A Nutridora",
    familia: "elementos",
    lugar: "Terra",
    frase: "Eu sustento tua jornada. Meus gestos são terra fértil.",
    palavras: ["Apoio", "Sustentação", "Constância"],
    essencia: "Gera e sustenta com generosidade silenciosa.",
    luz: "Dá suporte sem invadir. Nutre com presença firme.",
    sombra: "Sobrecarrega, se anula, espera retorno.",
    ativacao: "Cozinhe para alguém com intenção clara.",
    imagem: "/cartas/16.webp",
  },
  {
    n: 17,
    nome: "A Inspiradora",
    familia: "elementos",
    lugar: "Ar",
    frase: "Minha palavra sopra a mudança. Eu sou vento que guia.",
    palavras: ["Movimento", "Clareza", "Estímulo"],
    essencia: "Sopro que move ideias e abre espaço para o novo.",
    luz: "Provoca novos começos com leveza.",
    sombra: "Instável, dispersa, crítica demais.",
    ativacao: "Escreva uma ideia nova por dia, por sete dias.",
    imagem: "/cartas/17.webp",
  },
  {
    n: 18,
    nome: "A Incendiária",
    familia: "elementos",
    lugar: "Fogo",
    frase: "Eu queimo o que está pronto para partir. Minha paixão abre caminhos.",
    palavras: ["Impulso", "Renovação", "Intensidade"],
    essencia: "Fogo do impulso vital. Ativadora do novo.",
    luz: "Move com intensidade justa. Transforma pelo fogo.",
    sombra: "Impulsiva, destrutiva, sem direção.",
    ativacao: "O que em você está pronto para queimar?",
    imagem: "/cartas/18.webp",
  },
  {
    n: 19,
    nome: "A Emotiva",
    familia: "elementos",
    lugar: "Água",
    frase: "Eu choro, limpo e canto. Em mim, tudo retorna ao fluxo.",
    palavras: ["Sensibilidade", "Purificação", "Ciclo"],
    essencia: "Sente fundo. Transita entre águas internas.",
    luz: "Reconecta ao sentir profundo.",
    sombra: "Afogada em si, culpa os outros.",
    ativacao: "Mergulhe o rosto em água fria. Recomece.",
    imagem: "/cartas/19.webp",
  },
  {
    n: 20,
    nome: "A Grande Mãe",
    familia: "feminino",
    lugar: "Acolhimento",
    frase: "Eu alimento com silêncio. Em meus braços cabe o mundo.",
    palavras: ["Acolhimento", "Geração", "Presença"],
    essencia: "Presença que tudo nutre e dá forma.",
    luz: "Ampara sem dominar.",
    sombra: "Se dissolve no outro, exige retorno.",
    ativacao: "Ofereça silêncio pleno a alguém hoje.",
    imagem: "/cartas/20.webp",
  },
  {
    n: 21,
    nome: "A Filha Selvagem",
    familia: "feminino",
    lugar: "Instinto",
    frase: "Eu corro com os bichos. Minha liberdade não me doma.",
    palavras: ["Instinto", "Autenticidade", "Vitalidade"],
    essencia: "Liberdade crua. Voz do instinto.",
    luz: "Age sem filtro quando necessário.",
    sombra: "Reativa, impulsiva, ferida em nome da liberdade.",
    ativacao: "Corra ou grite num lugar aberto. Escute o que emerge depois.",
    imagem: "/cartas/21.webp",
  },
  {
    n: 22,
    nome: "A Amante Velada",
    familia: "feminino",
    lugar: "Intimidade",
    frase: "Eu sou templo e desejo. Minha pele sente o invisível.",
    palavras: ["Erotismo", "Mistério", "Receptividade"],
    essencia: "Intimidade protegida. Sedução ritual.",
    luz: "Vive a potência erótica como fonte de conexão.",
    sombra: "Manipula, seduz para preencher buracos.",
    ativacao: "Toque seu corpo como se fosse sagrado. O que desperta?",
    imagem: "/cartas/22.webp",
  },
  {
    n: 23,
    nome: "A Anciã das Estações",
    familia: "feminino",
    lugar: "Maturidade",
    frase: "Eu já fui todas. Minhas rugas são mapas do tempo.",
    palavras: ["Sabedoria", "Maturidade", "Integração"],
    essencia: "Ciclo da maturidade. Sabedoria do tempo.",
    luz: "Ensina sem dizer. Inspira só por ser.",
    sombra: "Amarga, desiludida, irônica.",
    ativacao: "Escreva 3 conselhos que você daria a si mesma de 10 anos atrás.",
    imagem: "/cartas/23.webp",
  },
  {
    n: 24,
    nome: "A Xamã do Sonho",
    familia: "feminino",
    lugar: "Sonho",
    frase: "Cruzo véus. Trago medicinas do sonho para a vida desperta.",
    palavras: ["Visão", "Revelação", "Transposição"],
    essencia: "Caminhante entre realidades. Porta onírica.",
    luz: "Caminha entre mundos com discernimento.",
    sombra: "Fuga pela via espiritual. Confunde viagem com evasão.",
    ativacao: "Anote seu próximo sonho. O que ele diz sobre seu agora?",
    imagem: "/cartas/24.webp",
  },
  {
    n: 25,
    nome: "A Arquiteta do Destino",
    familia: "feminino",
    lugar: "Destino",
    frase: "Em minhas mãos dançam os fios da realidade. Cada ponto é escolha consciente.",
    palavras: ["Construção", "Consciência", "Intenção"],
    essencia: "Construtora de realidades. Consciente.",
    luz: "Dá forma ao sonho com passos concretos.",
    sombra: "Quer controlar cada detalhe do caminho.",
    ativacao: "Desenhe a planta da vida que você quer habitar. Qual é o primeiro cômodo?",
    imagem: "/cartas/25.webp",
  },
  {
    n: 26,
    nome: "A Guardiã da Fonte",
    familia: "feminino",
    lugar: "Origem",
    frase: "Eu cuido da origem. Em mim mora a primeira palavra.",
    palavras: ["Mistério", "Origem", "Cuidado"],
    essencia: "Protege o mistério. Cuida da origem.",
    luz: "Preserva o que é essencial e o que nutre.",
    sombra: "Fecha-se demais, guarda o que pede para circular.",
    ativacao: "Beba um copo d'água devagar. Lembre de onde vem a sua força.",
    imagem: "/cartas/26.webp",
  },
  {
    n: 27,
    nome: "A Semeadora",
    familia: "lua",
    lugar: "Lua Nova",
    frase: "No escuro, eu planto. Tudo começa onde ninguém vê.",
    palavras: ["Intenção", "Potencial", "Confiança"],
    essencia: "Momento de plantar sem ver. Intenção profunda.",
    luz: "Sabe que tudo começa antes de aparecer.",
    sombra: "Desiste cedo por falta de retorno imediato.",
    ativacao: "Escreva uma intenção e enterre sob algo vivo: planta, pedra ou solo.",
    imagem: "/cartas/27.webp",
  },
  {
    n: 28,
    nome: "A Germinadora",
    familia: "lua",
    lugar: "Lua Crescente",
    frase: "Eu me ergo com firmeza. O broto vira caule.",
    palavras: ["Crescimento", "Estrutura", "Determinação"],
    essencia: "Primeira expansão. Coragem para emergir.",
    luz: "Persevera quando ainda é cedo.",
    sombra: "Força antes da hora, quer provas demais.",
    ativacao: "O que você começou que precisa agora de base? Nomeie e fortaleça.",
    imagem: "/cartas/28.webp",
  },
  {
    n: 29,
    nome: "A Radiante",
    familia: "lua",
    lugar: "Lua Cheia",
    frase: "Transbordo beleza e intenção. Minha luz é espelho.",
    palavras: ["Plenitude", "Expressão", "Espelho"],
    essencia: "Claridade total. Fruto da jornada.",
    luz: "Inspira pelo exemplo vivido.",
    sombra: "Exagera, ofusca, se perde em brilho vazio.",
    ativacao: "Reconheça uma conquista. Irradie isso com presença.",
    imagem: "/cartas/29.webp",
  },
  {
    n: 30,
    nome: "A Ceifadora",
    familia: "lua",
    lugar: "Lua Minguante",
    frase: "Eu solto o que não é mais meu. O fim é porta disfarçada.",
    palavras: ["Liberação", "Sabedoria", "Encerramento"],
    essencia: "Força que corta com amor. Liberação necessária.",
    luz: "Fecha com consciência.",
    sombra: "Se apega ao que já deveria ter ido.",
    ativacao: "Escreva algo que precisa soltar. Queime. Sinta o vazio fértil.",
    imagem: "/cartas/30.webp",
  },
];

/** As três posições da tiragem de imersão. */
export const posicoes = [
  { nome: "Raiz", pergunta: "O que sustenta este momento" },
  { nome: "Caule", pergunta: "O que pede movimento agora" },
  { nome: "Flor", pergunta: "O que pode desabrochar" },
] as const;

export function cartaPorNumero(n: number) {
  return cartas.find((c) => c.n === n);
}

export function familiaDe(carta: Carta) {
  return familias.find((f) => f.id === carta.familia)!;
}

export function romano(n: number) {
  const tabela: [number, string][] = [
    [10, "X"], [9, "IX"], [5, "V"], [4, "IV"], [1, "I"],
  ];
  let resto = n;
  let saida = "";
  for (const [valor, simbolo] of tabela) {
    while (resto >= valor) {
      saida += simbolo;
      resto -= valor;
    }
  }
  return saida;
}
